name: ArcadeCore
version: 0.0
main: me.softsheep6.arcadecore.ArcadeCore
api-version: 1.21.11
description: Core plugin for the Arcade SMP
author: softsheep6
contributors: []
website: https://softsheep6.github.io